language: csharp
dotnet: 2.1.300
install:
  - nuget install NUnit.Runners -version 3.8.0 -OutputDirectory testrunner
env:  
  - TEST_DIR=FSharp.Net
  - TEST_DIR=FSharp
  - TEST_DIR=CSharp.Net
script:
  - cd $TEST_DIR && /bin/bash build.sh  
  
