// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("SocialNetwork.Tests.NUnit")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String InternalsVisibleTo = "SocialNetwork.Tests.NUnit";
    }
}
